language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack:
    secure: KS9VYRNZr/VXBLs7BqKpRw98N3mtIute16yx2ILmxREYAYJMLRcWcDwlO8c6itIK13Db1d93bG1apFMC+WwRSh0O09lp/gQ3unSY4/qfxEUXGe3yzl2jVO+r5Jjd/xvA/Cm9VD/fAnF5XBYasrkYq9Qbn1PSWmApOSjlAxAgpz4=
deploy:
  provider: releases
  api_key:
    secure: gVeGuPbxqhLLyP3WUOsG3wYkQyYtTz/KHBZXS6hxsl7+h2wPCBl/DM5ht7ki0ZMJjVkADfAZ/qC16wrHZIlZEC8YB0LPkAoBENnCZcY1ymAalkC132IL8IVpALmy/doo+iuqsgPBWc3q3B26axo0CJDzrgX4SZVe791DOzgQWgM=
  file: Deploy/
  on:
    repo: slimshadeey1/WaveCloud
